IMPORT JAVAX.SWING.JBUTTON; IMPORT JAVAX.SWING.JFRAME;
PUBLIC CLASS LAYOUT {
PUBLIC STATIC VOID MAIN(STRING[] ARGS) (
JFRAME FRAME = NEW JFRAME("ABSOLUTE POSITIONING"); FRAME.SETDEFAULTCLOSEOPERATION(JFRAME.EXIT_ON_CLOSE):
FRAME.SETSIZE(400, 300):
// 1. DISABLE THE LAYOUT MANAGER
FRAME.SETLAYOUT(NULL):
JBUTTON BTN1 = NEW JBUTTON("BUTTON 1");
// 2. SET BOUNDS: (X, Y. WIDTH, HEIGHT)
II (50. 50) IS THE TOP-LEFT CORNER: 150PX WIDE, 40PX TALL BTN1.SETBOUNDS (50, 50, 150, 40):
JBUTTON BTN2= NEW JBUTTON("BUTTON 2");
// PLACE THIS ONE LOWER AND FURTHER RIGHT BTN2.SETBOUNDS (150, 120, 150, 40):
FRAME.ADD(BTN1): FRAME.ADD(BTN2):
FRAME.SETVISIBLE(TRUE);
}
